// Code generated by protoc-gen-go.
// source: copperd.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	copperd.proto

It has these top-level messages:
	Endpoint
	SubscribeOption
	PublishSettings
	Route
	SubscribeRequest
	SubscribeResponse
	GetEndpointsRequest
	GetEndpointsResponse
	StreamEndpointsRequest
	StreamEndpointsResponse
	UnsubscribeRequest
	UnsubscribeResponse
	PublishRequest
	PublishResponse
	UnpublishRequest
	UnpublishResponse
	SetRouteRequest
	SetRouteResponse
	ListRoutesRequest
	ListRoutesResponse
	LookupRouteRequest
	LookupRouteResponse
	StreamServicesRequest
	StreamServicesResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RequestType int32

const (
	RequestType_Subscribe       RequestType = 1
	RequestType_GetEndpoints    RequestType = 2
	RequestType_StreamEndpoints RequestType = 3
	RequestType_Unsubscribe     RequestType = 4
	RequestType_Publish         RequestType = 5
	RequestType_Unpublish       RequestType = 6
	RequestType_SetRoute        RequestType = 7
	RequestType_ListRoutes      RequestType = 8
	RequestType_LookupRoute     RequestType = 9
	RequestType_StreamServices  RequestType = 10
)

var RequestType_name = map[int32]string{
	1:  "Subscribe",
	2:  "GetEndpoints",
	3:  "StreamEndpoints",
	4:  "Unsubscribe",
	5:  "Publish",
	6:  "Unpublish",
	7:  "SetRoute",
	8:  "ListRoutes",
	9:  "LookupRoute",
	10: "StreamServices",
}
var RequestType_value = map[string]int32{
	"Subscribe":       1,
	"GetEndpoints":    2,
	"StreamEndpoints": 3,
	"Unsubscribe":     4,
	"Publish":         5,
	"Unpublish":       6,
	"SetRoute":        7,
	"ListRoutes":      8,
	"LookupRoute":     9,
	"StreamServices":  10,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}

type Endpoint struct {
	Network          *string `protobuf:"bytes,1,req,name=network" json:"network,omitempty"`
	Address          *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	TargetId         *int64  `protobuf:"zigzag64,3,opt,name=target_id" json:"target_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}

func (m *Endpoint) GetNetwork() string {
	if m != nil && m.Network != nil {
		return *m.Network
	}
	return ""
}

func (m *Endpoint) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *Endpoint) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type SubscribeOption struct {
	Service          *string `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	MinDistance      *uint32 `protobuf:"varint,2,opt,name=min_distance" json:"min_distance,omitempty"`
	MaxDistance      *uint32 `protobuf:"varint,3,opt,name=max_distance" json:"max_distance,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SubscribeOption) Reset()         { *m = SubscribeOption{} }
func (m *SubscribeOption) String() string { return proto.CompactTextString(m) }
func (*SubscribeOption) ProtoMessage()    {}

func (m *SubscribeOption) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *SubscribeOption) GetMinDistance() uint32 {
	if m != nil && m.MinDistance != nil {
		return *m.MinDistance
	}
	return 0
}

func (m *SubscribeOption) GetMaxDistance() uint32 {
	if m != nil && m.MaxDistance != nil {
		return *m.MaxDistance
	}
	return 0
}

type PublishSettings struct {
	Priority         *uint32 `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	Distance         *uint32 `protobuf:"varint,2,opt,name=distance" json:"distance,omitempty"`
	Concurrency      *uint32 `protobuf:"varint,3,opt,name=concurrency" json:"concurrency,omitempty"`
	QueueSize        *uint32 `protobuf:"varint,4,opt,name=queue_size" json:"queue_size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PublishSettings) Reset()         { *m = PublishSettings{} }
func (m *PublishSettings) String() string { return proto.CompactTextString(m) }
func (*PublishSettings) ProtoMessage()    {}

func (m *PublishSettings) GetPriority() uint32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *PublishSettings) GetDistance() uint32 {
	if m != nil && m.Distance != nil {
		return *m.Distance
	}
	return 0
}

func (m *PublishSettings) GetConcurrency() uint32 {
	if m != nil && m.Concurrency != nil {
		return *m.Concurrency
	}
	return 0
}

func (m *PublishSettings) GetQueueSize() uint32 {
	if m != nil && m.QueueSize != nil {
		return *m.QueueSize
	}
	return 0
}

type Route struct {
	Options          []*SubscribeOption `protobuf:"bytes,1,rep,name=options" json:"options,omitempty"`
	Weight           *uint32            `protobuf:"varint,2,req,name=weight" json:"weight,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}

func (m *Route) GetOptions() []*SubscribeOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Route) GetWeight() uint32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

type SubscribeRequest struct {
	Options          []*SubscribeOption `protobuf:"bytes,1,rep,name=options" json:"options,omitempty"`
	MaxRetries       *uint32            `protobuf:"varint,2,opt,name=max_retries" json:"max_retries,omitempty"`
	DisableRoutes    *bool              `protobuf:"varint,3,opt,name=disable_routes" json:"disable_routes,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}

func (m *SubscribeRequest) GetOptions() []*SubscribeOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *SubscribeRequest) GetMaxRetries() uint32 {
	if m != nil && m.MaxRetries != nil {
		return *m.MaxRetries
	}
	return 0
}

func (m *SubscribeRequest) GetDisableRoutes() bool {
	if m != nil && m.DisableRoutes != nil {
		return *m.DisableRoutes
	}
	return false
}

type SubscribeResponse struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}

func (m *SubscribeResponse) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type GetEndpointsRequest struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetEndpointsRequest) Reset()         { *m = GetEndpointsRequest{} }
func (m *GetEndpointsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEndpointsRequest) ProtoMessage()    {}

func (m *GetEndpointsRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type GetEndpointsResponse struct {
	Endpoints        []*Endpoint `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GetEndpointsResponse) Reset()         { *m = GetEndpointsResponse{} }
func (m *GetEndpointsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEndpointsResponse) ProtoMessage()    {}

func (m *GetEndpointsResponse) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type StreamEndpointsRequest struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StreamEndpointsRequest) Reset()         { *m = StreamEndpointsRequest{} }
func (m *StreamEndpointsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamEndpointsRequest) ProtoMessage()    {}

func (m *StreamEndpointsRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type StreamEndpointsResponse struct {
	Added            []*Endpoint `protobuf:"bytes,1,rep,name=added" json:"added,omitempty"`
	Removed          []*Endpoint `protobuf:"bytes,2,rep,name=removed" json:"removed,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *StreamEndpointsResponse) Reset()         { *m = StreamEndpointsResponse{} }
func (m *StreamEndpointsResponse) String() string { return proto.CompactTextString(m) }
func (*StreamEndpointsResponse) ProtoMessage()    {}

func (m *StreamEndpointsResponse) GetAdded() []*Endpoint {
	if m != nil {
		return m.Added
	}
	return nil
}

func (m *StreamEndpointsResponse) GetRemoved() []*Endpoint {
	if m != nil {
		return m.Removed
	}
	return nil
}

type UnsubscribeRequest struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}

func (m *UnsubscribeRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type UnsubscribeResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnsubscribeResponse) Reset()         { *m = UnsubscribeResponse{} }
func (m *UnsubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeResponse) ProtoMessage()    {}

type PublishRequest struct {
	TargetId         *int64           `protobuf:"zigzag64,1,req,name=target_id" json:"target_id,omitempty"`
	Name             *string          `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Settings         *PublishSettings `protobuf:"bytes,3,req,name=settings" json:"settings,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}

func (m *PublishRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

func (m *PublishRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PublishRequest) GetSettings() *PublishSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type PublishResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}

type UnpublishRequest struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnpublishRequest) Reset()         { *m = UnpublishRequest{} }
func (m *UnpublishRequest) String() string { return proto.CompactTextString(m) }
func (*UnpublishRequest) ProtoMessage()    {}

func (m *UnpublishRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type UnpublishResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnpublishResponse) Reset()         { *m = UnpublishResponse{} }
func (m *UnpublishResponse) String() string { return proto.CompactTextString(m) }
func (*UnpublishResponse) ProtoMessage()    {}

type SetRouteRequest struct {
	Name             *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Routes           []*Route `protobuf:"bytes,2,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SetRouteRequest) Reset()         { *m = SetRouteRequest{} }
func (m *SetRouteRequest) String() string { return proto.CompactTextString(m) }
func (*SetRouteRequest) ProtoMessage()    {}

func (m *SetRouteRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SetRouteRequest) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type SetRouteResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetRouteResponse) Reset()         { *m = SetRouteResponse{} }
func (m *SetRouteResponse) String() string { return proto.CompactTextString(m) }
func (*SetRouteResponse) ProtoMessage()    {}

type ListRoutesRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListRoutesRequest) Reset()         { *m = ListRoutesRequest{} }
func (m *ListRoutesRequest) String() string { return proto.CompactTextString(m) }
func (*ListRoutesRequest) ProtoMessage()    {}

type ListRoutesResponse struct {
	Names            []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ListRoutesResponse) Reset()         { *m = ListRoutesResponse{} }
func (m *ListRoutesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRoutesResponse) ProtoMessage()    {}

func (m *ListRoutesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type LookupRouteRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LookupRouteRequest) Reset()         { *m = LookupRouteRequest{} }
func (m *LookupRouteRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRouteRequest) ProtoMessage()    {}

func (m *LookupRouteRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type LookupRouteResponse struct {
	Routes           []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *LookupRouteResponse) Reset()         { *m = LookupRouteResponse{} }
func (m *LookupRouteResponse) String() string { return proto.CompactTextString(m) }
func (*LookupRouteResponse) ProtoMessage()    {}

func (m *LookupRouteResponse) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type StreamServicesRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StreamServicesRequest) Reset()         { *m = StreamServicesRequest{} }
func (m *StreamServicesRequest) String() string { return proto.CompactTextString(m) }
func (*StreamServicesRequest) ProtoMessage()    {}

type StreamServicesResponse struct {
	TargetId         *int64           `protobuf:"zigzag64,1,req,name=target_id" json:"target_id,omitempty"`
	Name             *string          `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Settings         *PublishSettings `protobuf:"bytes,3,req,name=settings" json:"settings,omitempty"`
	Valid            *bool            `protobuf:"varint,4,req,name=valid" json:"valid,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *StreamServicesResponse) Reset()         { *m = StreamServicesResponse{} }
func (m *StreamServicesResponse) String() string { return proto.CompactTextString(m) }
func (*StreamServicesResponse) ProtoMessage()    {}

func (m *StreamServicesResponse) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

func (m *StreamServicesResponse) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *StreamServicesResponse) GetSettings() *PublishSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *StreamServicesResponse) GetValid() bool {
	if m != nil && m.Valid != nil {
		return *m.Valid
	}
	return false
}

func init() {
	proto.RegisterEnum("protocol.RequestType", RequestType_name, RequestType_value)
}
