// Code generated by protoc-gen-go. DO NOT EDIT.
// source: copper.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	copper.proto

It has these top-level messages:
	Endpoint
	SubscribeOption
	PublishSettings
	Route
	ServiceChange
	SubscribeRequest
	SubscribeResponse
	GetEndpointsRequest
	GetEndpointsResponse
	StreamEndpointsRequest
	StreamEndpointsResponse
	UnsubscribeRequest
	UnsubscribeResponse
	PublishRequest
	PublishResponse
	UnpublishRequest
	UnpublishResponse
	SetRouteRequest
	SetRouteResponse
	ListRoutesRequest
	ListRoutesResponse
	LookupRouteRequest
	LookupRouteResponse
	StreamServicesRequest
	StreamServicesResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_NewStream       RequestType = 0
	RequestType_Subscribe       RequestType = 1
	RequestType_GetEndpoints    RequestType = 2
	RequestType_StreamEndpoints RequestType = 3
	RequestType_Unsubscribe     RequestType = 4
	RequestType_Publish         RequestType = 5
	RequestType_Unpublish       RequestType = 6
	RequestType_SetRoute        RequestType = 7
	RequestType_ListRoutes      RequestType = 8
	RequestType_LookupRoute     RequestType = 9
	RequestType_StreamServices  RequestType = 10
)

var RequestType_name = map[int32]string{
	0:  "NewStream",
	1:  "Subscribe",
	2:  "GetEndpoints",
	3:  "StreamEndpoints",
	4:  "Unsubscribe",
	5:  "Publish",
	6:  "Unpublish",
	7:  "SetRoute",
	8:  "ListRoutes",
	9:  "LookupRoute",
	10: "StreamServices",
}
var RequestType_value = map[string]int32{
	"NewStream":       0,
	"Subscribe":       1,
	"GetEndpoints":    2,
	"StreamEndpoints": 3,
	"Unsubscribe":     4,
	"Publish":         5,
	"Unpublish":       6,
	"SetRoute":        7,
	"ListRoutes":      8,
	"LookupRoute":     9,
	"StreamServices":  10,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Endpoint struct {
	Network          *string `protobuf:"bytes,1,req,name=network" json:"network,omitempty"`
	Address          *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	TargetId         *int64  `protobuf:"zigzag64,3,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Endpoint) GetNetwork() string {
	if m != nil && m.Network != nil {
		return *m.Network
	}
	return ""
}

func (m *Endpoint) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *Endpoint) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type SubscribeOption struct {
	Service          *string `protobuf:"bytes,1,req,name=service" json:"service,omitempty"`
	MinDistance      *uint32 `protobuf:"varint,2,opt,name=min_distance,json=minDistance" json:"min_distance,omitempty"`
	MaxDistance      *uint32 `protobuf:"varint,3,opt,name=max_distance,json=maxDistance" json:"max_distance,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SubscribeOption) Reset()                    { *m = SubscribeOption{} }
func (m *SubscribeOption) String() string            { return proto.CompactTextString(m) }
func (*SubscribeOption) ProtoMessage()               {}
func (*SubscribeOption) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubscribeOption) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

func (m *SubscribeOption) GetMinDistance() uint32 {
	if m != nil && m.MinDistance != nil {
		return *m.MinDistance
	}
	return 0
}

func (m *SubscribeOption) GetMaxDistance() uint32 {
	if m != nil && m.MaxDistance != nil {
		return *m.MaxDistance
	}
	return 0
}

type PublishSettings struct {
	Priority         *uint32 `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	MaxDistance      *uint32 `protobuf:"varint,2,opt,name=max_distance,json=maxDistance" json:"max_distance,omitempty"`
	Concurrency      *uint32 `protobuf:"varint,3,opt,name=concurrency" json:"concurrency,omitempty"`
	QueueSize        *uint32 `protobuf:"varint,4,opt,name=queue_size,json=queueSize" json:"queue_size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PublishSettings) Reset()                    { *m = PublishSettings{} }
func (m *PublishSettings) String() string            { return proto.CompactTextString(m) }
func (*PublishSettings) ProtoMessage()               {}
func (*PublishSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PublishSettings) GetPriority() uint32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *PublishSettings) GetMaxDistance() uint32 {
	if m != nil && m.MaxDistance != nil {
		return *m.MaxDistance
	}
	return 0
}

func (m *PublishSettings) GetConcurrency() uint32 {
	if m != nil && m.Concurrency != nil {
		return *m.Concurrency
	}
	return 0
}

func (m *PublishSettings) GetQueueSize() uint32 {
	if m != nil && m.QueueSize != nil {
		return *m.QueueSize
	}
	return 0
}

type Route struct {
	Options          []*SubscribeOption `protobuf:"bytes,1,rep,name=options" json:"options,omitempty"`
	Weight           *uint32            `protobuf:"varint,2,req,name=weight" json:"weight,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Route) GetOptions() []*SubscribeOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Route) GetWeight() uint32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

type ServiceChange struct {
	TargetId         *int64           `protobuf:"zigzag64,1,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	Name             *string          `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Settings         *PublishSettings `protobuf:"bytes,3,req,name=settings" json:"settings,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ServiceChange) Reset()                    { *m = ServiceChange{} }
func (m *ServiceChange) String() string            { return proto.CompactTextString(m) }
func (*ServiceChange) ProtoMessage()               {}
func (*ServiceChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServiceChange) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

func (m *ServiceChange) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ServiceChange) GetSettings() *PublishSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type SubscribeRequest struct {
	Options          []*SubscribeOption `protobuf:"bytes,1,rep,name=options" json:"options,omitempty"`
	DisableRoutes    *bool              `protobuf:"varint,2,opt,name=disable_routes,json=disableRoutes" json:"disable_routes,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SubscribeRequest) GetOptions() []*SubscribeOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *SubscribeRequest) GetDisableRoutes() bool {
	if m != nil && m.DisableRoutes != nil {
		return *m.DisableRoutes
	}
	return false
}

type SubscribeResponse struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SubscribeResponse) Reset()                    { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()               {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SubscribeResponse) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type GetEndpointsRequest struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetEndpointsRequest) Reset()                    { *m = GetEndpointsRequest{} }
func (m *GetEndpointsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEndpointsRequest) ProtoMessage()               {}
func (*GetEndpointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetEndpointsRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type GetEndpointsResponse struct {
	Endpoints        []*Endpoint `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GetEndpointsResponse) Reset()                    { *m = GetEndpointsResponse{} }
func (m *GetEndpointsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEndpointsResponse) ProtoMessage()               {}
func (*GetEndpointsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetEndpointsResponse) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type StreamEndpointsRequest struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *StreamEndpointsRequest) Reset()                    { *m = StreamEndpointsRequest{} }
func (m *StreamEndpointsRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamEndpointsRequest) ProtoMessage()               {}
func (*StreamEndpointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StreamEndpointsRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type StreamEndpointsResponse struct {
	Added            []*Endpoint `protobuf:"bytes,1,rep,name=added" json:"added,omitempty"`
	Removed          []*Endpoint `protobuf:"bytes,2,rep,name=removed" json:"removed,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *StreamEndpointsResponse) Reset()                    { *m = StreamEndpointsResponse{} }
func (m *StreamEndpointsResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamEndpointsResponse) ProtoMessage()               {}
func (*StreamEndpointsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StreamEndpointsResponse) GetAdded() []*Endpoint {
	if m != nil {
		return m.Added
	}
	return nil
}

func (m *StreamEndpointsResponse) GetRemoved() []*Endpoint {
	if m != nil {
		return m.Removed
	}
	return nil
}

type UnsubscribeRequest struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnsubscribeRequest) Reset()                    { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()               {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UnsubscribeRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type UnsubscribeResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnsubscribeResponse) Reset()                    { *m = UnsubscribeResponse{} }
func (m *UnsubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*UnsubscribeResponse) ProtoMessage()               {}
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type PublishRequest struct {
	TargetId         *int64           `protobuf:"zigzag64,1,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	Name             *string          `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Settings         *PublishSettings `protobuf:"bytes,3,req,name=settings" json:"settings,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PublishRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

func (m *PublishRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PublishRequest) GetSettings() *PublishSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type PublishResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type UnpublishRequest struct {
	TargetId         *int64 `protobuf:"zigzag64,1,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnpublishRequest) Reset()                    { *m = UnpublishRequest{} }
func (m *UnpublishRequest) String() string            { return proto.CompactTextString(m) }
func (*UnpublishRequest) ProtoMessage()               {}
func (*UnpublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UnpublishRequest) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type UnpublishResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnpublishResponse) Reset()                    { *m = UnpublishResponse{} }
func (m *UnpublishResponse) String() string            { return proto.CompactTextString(m) }
func (*UnpublishResponse) ProtoMessage()               {}
func (*UnpublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type SetRouteRequest struct {
	Name             *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Routes           []*Route `protobuf:"bytes,2,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SetRouteRequest) Reset()                    { *m = SetRouteRequest{} }
func (m *SetRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRouteRequest) ProtoMessage()               {}
func (*SetRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SetRouteRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SetRouteRequest) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type SetRouteResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetRouteResponse) Reset()                    { *m = SetRouteResponse{} }
func (m *SetRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*SetRouteResponse) ProtoMessage()               {}
func (*SetRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type ListRoutesRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListRoutesRequest) Reset()                    { *m = ListRoutesRequest{} }
func (m *ListRoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRoutesRequest) ProtoMessage()               {}
func (*ListRoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type ListRoutesResponse struct {
	Names            []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ListRoutesResponse) Reset()                    { *m = ListRoutesResponse{} }
func (m *ListRoutesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListRoutesResponse) ProtoMessage()               {}
func (*ListRoutesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ListRoutesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type LookupRouteRequest struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LookupRouteRequest) Reset()                    { *m = LookupRouteRequest{} }
func (m *LookupRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*LookupRouteRequest) ProtoMessage()               {}
func (*LookupRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *LookupRouteRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type LookupRouteResponse struct {
	Routes           []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *LookupRouteResponse) Reset()                    { *m = LookupRouteResponse{} }
func (m *LookupRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupRouteResponse) ProtoMessage()               {}
func (*LookupRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *LookupRouteResponse) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type StreamServicesRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StreamServicesRequest) Reset()                    { *m = StreamServicesRequest{} }
func (m *StreamServicesRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamServicesRequest) ProtoMessage()               {}
func (*StreamServicesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type StreamServicesResponse struct {
	Removed          []int64          `protobuf:"zigzag64,1,rep,packed,name=removed" json:"removed,omitempty"`
	Changed          []*ServiceChange `protobuf:"bytes,2,rep,name=changed" json:"changed,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *StreamServicesResponse) Reset()                    { *m = StreamServicesResponse{} }
func (m *StreamServicesResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamServicesResponse) ProtoMessage()               {}
func (*StreamServicesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *StreamServicesResponse) GetRemoved() []int64 {
	if m != nil {
		return m.Removed
	}
	return nil
}

func (m *StreamServicesResponse) GetChanged() []*ServiceChange {
	if m != nil {
		return m.Changed
	}
	return nil
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "protocol.Endpoint")
	proto.RegisterType((*SubscribeOption)(nil), "protocol.SubscribeOption")
	proto.RegisterType((*PublishSettings)(nil), "protocol.PublishSettings")
	proto.RegisterType((*Route)(nil), "protocol.Route")
	proto.RegisterType((*ServiceChange)(nil), "protocol.ServiceChange")
	proto.RegisterType((*SubscribeRequest)(nil), "protocol.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "protocol.SubscribeResponse")
	proto.RegisterType((*GetEndpointsRequest)(nil), "protocol.GetEndpointsRequest")
	proto.RegisterType((*GetEndpointsResponse)(nil), "protocol.GetEndpointsResponse")
	proto.RegisterType((*StreamEndpointsRequest)(nil), "protocol.StreamEndpointsRequest")
	proto.RegisterType((*StreamEndpointsResponse)(nil), "protocol.StreamEndpointsResponse")
	proto.RegisterType((*UnsubscribeRequest)(nil), "protocol.UnsubscribeRequest")
	proto.RegisterType((*UnsubscribeResponse)(nil), "protocol.UnsubscribeResponse")
	proto.RegisterType((*PublishRequest)(nil), "protocol.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "protocol.PublishResponse")
	proto.RegisterType((*UnpublishRequest)(nil), "protocol.UnpublishRequest")
	proto.RegisterType((*UnpublishResponse)(nil), "protocol.UnpublishResponse")
	proto.RegisterType((*SetRouteRequest)(nil), "protocol.SetRouteRequest")
	proto.RegisterType((*SetRouteResponse)(nil), "protocol.SetRouteResponse")
	proto.RegisterType((*ListRoutesRequest)(nil), "protocol.ListRoutesRequest")
	proto.RegisterType((*ListRoutesResponse)(nil), "protocol.ListRoutesResponse")
	proto.RegisterType((*LookupRouteRequest)(nil), "protocol.LookupRouteRequest")
	proto.RegisterType((*LookupRouteResponse)(nil), "protocol.LookupRouteResponse")
	proto.RegisterType((*StreamServicesRequest)(nil), "protocol.StreamServicesRequest")
	proto.RegisterType((*StreamServicesResponse)(nil), "protocol.StreamServicesResponse")
	proto.RegisterEnum("protocol.RequestType", RequestType_name, RequestType_value)
}

func init() { proto.RegisterFile("copper.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 735 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdb, 0x6e, 0xdb, 0x38,
	0x10, 0x5d, 0xc9, 0x71, 0x2c, 0x8f, 0x6f, 0x34, 0x9d, 0x8b, 0xf6, 0x06, 0x78, 0x09, 0x2c, 0xd6,
	0x08, 0x16, 0x69, 0x92, 0x22, 0xaf, 0x7d, 0xe8, 0x05, 0x6d, 0x81, 0x20, 0x2d, 0xe4, 0xe4, 0xa9,
	0x0f, 0x86, 0x2c, 0x11, 0x0e, 0x91, 0x98, 0x94, 0x45, 0x2a, 0x4e, 0xf2, 0x17, 0xfd, 0xa5, 0x7e,
	0x59, 0x21, 0x89, 0x94, 0x64, 0x07, 0x75, 0xd3, 0xa2, 0x4f, 0xf6, 0x0c, 0xcf, 0xcc, 0x1c, 0x9e,
	0x39, 0x22, 0xb4, 0x03, 0x11, 0x45, 0x34, 0x3e, 0x8c, 0x62, 0xa1, 0x04, 0x76, 0xb2, 0x9f, 0x40,
	0xdc, 0x90, 0x4f, 0xe0, 0xbc, 0xe1, 0x61, 0x24, 0x18, 0x57, 0xd8, 0x85, 0x06, 0xa7, 0x6a, 0x29,
	0xe2, 0x6b, 0xd7, 0x1a, 0xda, 0xa3, 0xa6, 0x67, 0xc2, 0xf4, 0xc4, 0x0f, 0xc3, 0x98, 0x4a, 0xe9,
	0xda, 0xf9, 0x89, 0x0e, 0xf1, 0x9f, 0xd0, 0x54, 0x7e, 0x3c, 0xa3, 0x6a, 0xc2, 0x42, 0xb7, 0x36,
	0xb4, 0x46, 0xd8, 0x73, 0xf2, 0xc4, 0xfb, 0x90, 0x2c, 0xa0, 0x37, 0x4e, 0xa6, 0x32, 0x88, 0xd9,
	0x94, 0x7e, 0x88, 0x14, 0x13, 0x3c, 0xed, 0x24, 0x69, 0x7c, 0xcb, 0x02, 0x6a, 0x66, 0xe8, 0x10,
	0xff, 0x03, 0xed, 0x39, 0xe3, 0x93, 0x90, 0x49, 0xe5, 0xf3, 0x80, 0xba, 0xf6, 0xd0, 0x1a, 0x75,
	0xbc, 0xd6, 0x9c, 0xf1, 0xd7, 0x3a, 0x95, 0x41, 0xfc, 0xbb, 0x12, 0x52, 0xd3, 0x10, 0xff, 0xce,
	0x40, 0xc8, 0x67, 0x0b, 0x7a, 0x1f, 0x93, 0xe9, 0x0d, 0x93, 0x57, 0x63, 0xaa, 0x14, 0xe3, 0x33,
	0x89, 0xff, 0x00, 0x27, 0x8a, 0x99, 0x88, 0x99, 0xba, 0x77, 0xad, 0xac, 0xa4, 0x88, 0x1f, 0xb5,
	0xb4, 0x1f, 0xb5, 0xc4, 0x43, 0x68, 0x05, 0x82, 0x07, 0x49, 0x1c, 0x53, 0x1e, 0xdc, 0x9b, 0xa1,
	0x95, 0x14, 0xfe, 0x1b, 0x60, 0x91, 0xd0, 0x84, 0x4e, 0x24, 0x7b, 0xa0, 0xee, 0x56, 0x06, 0x68,
	0x66, 0x99, 0x31, 0x7b, 0xa0, 0xe4, 0x02, 0xea, 0x9e, 0x48, 0x14, 0xc5, 0xcf, 0xa1, 0x21, 0x32,
	0x19, 0xa4, 0x6b, 0x0d, 0x6b, 0xa3, 0xd6, 0xc9, 0xef, 0x87, 0x66, 0x11, 0x87, 0x6b, 0x42, 0x79,
	0x06, 0x89, 0xf7, 0x60, 0x7b, 0x49, 0xd9, 0xec, 0x4a, 0x65, 0xd2, 0x77, 0x3c, 0x1d, 0x91, 0x25,
	0x74, 0xc6, 0xb9, 0x74, 0xaf, 0xae, 0x7c, 0x3e, 0xa3, 0xab, 0xab, 0x48, 0xc5, 0xad, 0xac, 0x02,
	0x63, 0xd8, 0xe2, 0xfe, 0x9c, 0xea, 0xf5, 0x65, 0xff, 0xf1, 0x29, 0x38, 0x52, 0x6b, 0xe4, 0xd6,
	0x86, 0xf6, 0x2a, 0x9f, 0x35, 0x11, 0xbd, 0x02, 0x4a, 0x38, 0xa0, 0x82, 0xac, 0x47, 0x17, 0x09,
	0x95, 0xea, 0xe7, 0x6e, 0xf6, 0x2f, 0x74, 0x43, 0x26, 0xfd, 0xe9, 0x0d, 0x9d, 0xc4, 0xa9, 0x3e,
	0x32, 0x53, 0xdf, 0xf1, 0x3a, 0x3a, 0x9b, 0x89, 0x26, 0xc9, 0x11, 0xf4, 0x2b, 0xf3, 0x64, 0x24,
	0xb8, 0xdc, 0x7c, 0x59, 0x72, 0x02, 0x83, 0xb7, 0x54, 0x19, 0x5f, 0x4b, 0x43, 0x72, 0x63, 0xcd,
	0x3b, 0xd8, 0x59, 0xad, 0xd1, 0x83, 0x8e, 0xa0, 0x49, 0x4d, 0x52, 0xdf, 0x0d, 0x97, 0x77, 0x33,
	0x78, 0xaf, 0x04, 0x91, 0x53, 0xd8, 0x1b, 0xab, 0x98, 0xfa, 0xf3, 0x1f, 0x23, 0xb0, 0x80, 0xfd,
	0x47, 0x65, 0x9a, 0xc3, 0x08, 0xea, 0x7e, 0x18, 0xd2, 0x70, 0xc3, 0xfc, 0x1c, 0x80, 0xff, 0x87,
	0x46, 0x4c, 0xe7, 0xe2, 0x96, 0x86, 0xae, 0xfd, 0x4d, 0xac, 0x81, 0x90, 0x63, 0xc0, 0x97, 0x5c,
	0xae, 0xef, 0x72, 0x23, 0xcb, 0x5d, 0x18, 0xac, 0x94, 0xe4, 0x0c, 0xc9, 0x1d, 0x74, 0xb5, 0x61,
	0x9e, 0xd2, 0xe5, 0x57, 0xba, 0xb1, 0x5f, 0x7c, 0xef, 0x05, 0x99, 0x67, 0x80, 0x2e, 0x79, 0xf4,
	0x74, 0x3a, 0x64, 0x00, 0xfd, 0x4a, 0x81, 0xee, 0x72, 0x0e, 0xbd, 0x31, 0x55, 0x99, 0x07, 0x4d,
	0x13, 0x43, 0xdb, 0xaa, 0xd0, 0xfe, 0x0f, 0xb6, 0x0b, 0xf3, 0xa6, 0x82, 0xf7, 0x4a, 0xd2, 0x79,
	0xad, 0x3e, 0x26, 0x18, 0x50, 0xd9, 0x4f, 0xcf, 0x18, 0x40, 0xff, 0x8c, 0xc9, 0x3c, 0x69, 0x5c,
	0x42, 0x0e, 0x00, 0x57, 0x93, 0xda, 0x03, 0x3b, 0x50, 0x4f, 0xe7, 0xe5, 0x1e, 0x6c, 0x7a, 0x79,
	0x40, 0x46, 0x80, 0xcf, 0x84, 0xb8, 0x4e, 0xa2, 0xef, 0xf1, 0x24, 0x2f, 0x60, 0xb0, 0x82, 0xd4,
	0x6d, 0x4b, 0xfa, 0xd6, 0x66, 0xfa, 0xfb, 0xb0, 0x9b, 0xdb, 0x53, 0x3f, 0x3a, 0x05, 0x5d, 0x66,
	0xec, 0x5e, 0x1e, 0xe8, 0xde, 0x7f, 0x95, 0x66, 0x4c, 0x9b, 0xe3, 0x97, 0x36, 0xb2, 0x0a, 0xf3,
	0xe1, 0x63, 0x68, 0x04, 0xd9, 0xc3, 0x65, 0xac, 0xba, 0x5f, 0x79, 0x32, 0xaa, 0x0f, 0x9b, 0x67,
	0x70, 0x07, 0x5f, 0x2c, 0x68, 0xe9, 0xb1, 0x17, 0xf7, 0x11, 0xc5, 0x1d, 0x68, 0x9e, 0xd3, 0x65,
	0x3e, 0x1d, 0xfd, 0x96, 0x86, 0xc5, 0x43, 0x81, 0x2c, 0x8c, 0xa0, 0x5d, 0xfd, 0xa2, 0x91, 0x8d,
	0x07, 0xd0, 0x5b, 0xfb, 0xc4, 0x50, 0x0d, 0xf7, 0xa0, 0x55, 0x71, 0x34, 0xda, 0xc2, 0x2d, 0x68,
	0x68, 0x47, 0xa1, 0x7a, 0xda, 0xb3, 0xb0, 0x06, 0xda, 0xc6, 0x6d, 0x70, 0xcc, 0x12, 0x51, 0x03,
	0x77, 0x01, 0xca, 0x4d, 0x21, 0x27, 0x6d, 0x55, 0xd1, 0x18, 0x35, 0x31, 0x86, 0xee, 0xaa, 0x36,
	0x08, 0xbe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x25, 0x28, 0x37, 0x3a, 0x8a, 0x07, 0x00, 0x00,
}
