// Code generated by protoc-gen-go. DO NOT EDIT.
// source: copper.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	copper.proto

It has these top-level messages:
	Endpoint
	SubscribeOption
	PublishSettings
	Route
	ServiceChange
	SubscribeRequest
	SubscribeResponse
	GetEndpointsRequest
	GetEndpointsResponse
	StreamEndpointsRequest
	StreamEndpointsResponse
	UnsubscribeRequest
	UnsubscribeResponse
	PublishRequest
	PublishResponse
	UnpublishRequest
	UnpublishResponse
	SetRouteRequest
	SetRouteResponse
	ListRoutesRequest
	ListRoutesResponse
	LookupRouteRequest
	LookupRouteResponse
	StreamServicesRequest
	StreamServicesResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_NewStream       RequestType = 0
	RequestType_Subscribe       RequestType = 1
	RequestType_GetEndpoints    RequestType = 2
	RequestType_StreamEndpoints RequestType = 3
	RequestType_Unsubscribe     RequestType = 4
	RequestType_Publish         RequestType = 5
	RequestType_Unpublish       RequestType = 6
	RequestType_SetRoute        RequestType = 7
	RequestType_ListRoutes      RequestType = 8
	RequestType_LookupRoute     RequestType = 9
	RequestType_StreamServices  RequestType = 10
)

var RequestType_name = map[int32]string{
	0:  "NewStream",
	1:  "Subscribe",
	2:  "GetEndpoints",
	3:  "StreamEndpoints",
	4:  "Unsubscribe",
	5:  "Publish",
	6:  "Unpublish",
	7:  "SetRoute",
	8:  "ListRoutes",
	9:  "LookupRoute",
	10: "StreamServices",
}
var RequestType_value = map[string]int32{
	"NewStream":       0,
	"Subscribe":       1,
	"GetEndpoints":    2,
	"StreamEndpoints": 3,
	"Unsubscribe":     4,
	"Publish":         5,
	"Unpublish":       6,
	"SetRoute":        7,
	"ListRoutes":      8,
	"LookupRoute":     9,
	"StreamServices":  10,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Endpoint struct {
	Network  string `protobuf:"bytes,1,opt,name=network" json:"network,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	TargetId int64  `protobuf:"zigzag64,3,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Endpoint) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Endpoint) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Endpoint) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

type SubscribeOption struct {
	Service     string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	MinDistance uint32 `protobuf:"varint,2,opt,name=min_distance,json=minDistance" json:"min_distance,omitempty"`
	MaxDistance uint32 `protobuf:"varint,3,opt,name=max_distance,json=maxDistance" json:"max_distance,omitempty"`
}

func (m *SubscribeOption) Reset()                    { *m = SubscribeOption{} }
func (m *SubscribeOption) String() string            { return proto.CompactTextString(m) }
func (*SubscribeOption) ProtoMessage()               {}
func (*SubscribeOption) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubscribeOption) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SubscribeOption) GetMinDistance() uint32 {
	if m != nil {
		return m.MinDistance
	}
	return 0
}

func (m *SubscribeOption) GetMaxDistance() uint32 {
	if m != nil {
		return m.MaxDistance
	}
	return 0
}

type PublishSettings struct {
	Priority    uint32 `protobuf:"varint,1,opt,name=priority" json:"priority,omitempty"`
	MaxDistance uint32 `protobuf:"varint,2,opt,name=max_distance,json=maxDistance" json:"max_distance,omitempty"`
	Concurrency uint32 `protobuf:"varint,3,opt,name=concurrency" json:"concurrency,omitempty"`
	QueueSize   uint32 `protobuf:"varint,4,opt,name=queue_size,json=queueSize" json:"queue_size,omitempty"`
}

func (m *PublishSettings) Reset()                    { *m = PublishSettings{} }
func (m *PublishSettings) String() string            { return proto.CompactTextString(m) }
func (*PublishSettings) ProtoMessage()               {}
func (*PublishSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PublishSettings) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *PublishSettings) GetMaxDistance() uint32 {
	if m != nil {
		return m.MaxDistance
	}
	return 0
}

func (m *PublishSettings) GetConcurrency() uint32 {
	if m != nil {
		return m.Concurrency
	}
	return 0
}

func (m *PublishSettings) GetQueueSize() uint32 {
	if m != nil {
		return m.QueueSize
	}
	return 0
}

type Route struct {
	Options []*SubscribeOption `protobuf:"bytes,1,rep,name=options" json:"options,omitempty"`
	Weight  uint32             `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Route) GetOptions() []*SubscribeOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Route) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type ServiceChange struct {
	TargetId int64            `protobuf:"zigzag64,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	Name     string           `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Settings *PublishSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
}

func (m *ServiceChange) Reset()                    { *m = ServiceChange{} }
func (m *ServiceChange) String() string            { return proto.CompactTextString(m) }
func (*ServiceChange) ProtoMessage()               {}
func (*ServiceChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ServiceChange) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *ServiceChange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceChange) GetSettings() *PublishSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type SubscribeRequest struct {
	Options       []*SubscribeOption `protobuf:"bytes,1,rep,name=options" json:"options,omitempty"`
	DisableRoutes bool               `protobuf:"varint,2,opt,name=disable_routes,json=disableRoutes" json:"disable_routes,omitempty"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SubscribeRequest) GetOptions() []*SubscribeOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *SubscribeRequest) GetDisableRoutes() bool {
	if m != nil {
		return m.DisableRoutes
	}
	return false
}

type SubscribeResponse struct {
	TargetId int64 `protobuf:"zigzag64,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
}

func (m *SubscribeResponse) Reset()                    { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()               {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SubscribeResponse) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

type GetEndpointsRequest struct {
	TargetId int64 `protobuf:"zigzag64,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
}

func (m *GetEndpointsRequest) Reset()                    { *m = GetEndpointsRequest{} }
func (m *GetEndpointsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEndpointsRequest) ProtoMessage()               {}
func (*GetEndpointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetEndpointsRequest) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

type GetEndpointsResponse struct {
	Endpoints []*Endpoint `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
}

func (m *GetEndpointsResponse) Reset()                    { *m = GetEndpointsResponse{} }
func (m *GetEndpointsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEndpointsResponse) ProtoMessage()               {}
func (*GetEndpointsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetEndpointsResponse) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type StreamEndpointsRequest struct {
	TargetId int64 `protobuf:"zigzag64,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
}

func (m *StreamEndpointsRequest) Reset()                    { *m = StreamEndpointsRequest{} }
func (m *StreamEndpointsRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamEndpointsRequest) ProtoMessage()               {}
func (*StreamEndpointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StreamEndpointsRequest) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

type StreamEndpointsResponse struct {
	Added   []*Endpoint `protobuf:"bytes,1,rep,name=added" json:"added,omitempty"`
	Removed []*Endpoint `protobuf:"bytes,2,rep,name=removed" json:"removed,omitempty"`
}

func (m *StreamEndpointsResponse) Reset()                    { *m = StreamEndpointsResponse{} }
func (m *StreamEndpointsResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamEndpointsResponse) ProtoMessage()               {}
func (*StreamEndpointsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StreamEndpointsResponse) GetAdded() []*Endpoint {
	if m != nil {
		return m.Added
	}
	return nil
}

func (m *StreamEndpointsResponse) GetRemoved() []*Endpoint {
	if m != nil {
		return m.Removed
	}
	return nil
}

type UnsubscribeRequest struct {
	TargetId int64 `protobuf:"zigzag64,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
}

func (m *UnsubscribeRequest) Reset()                    { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()               {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UnsubscribeRequest) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

type UnsubscribeResponse struct {
}

func (m *UnsubscribeResponse) Reset()                    { *m = UnsubscribeResponse{} }
func (m *UnsubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*UnsubscribeResponse) ProtoMessage()               {}
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type PublishRequest struct {
	TargetId int64            `protobuf:"zigzag64,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	Name     string           `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Settings *PublishSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PublishRequest) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *PublishRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublishRequest) GetSettings() *PublishSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type PublishResponse struct {
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type UnpublishRequest struct {
	TargetId int64 `protobuf:"zigzag64,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
}

func (m *UnpublishRequest) Reset()                    { *m = UnpublishRequest{} }
func (m *UnpublishRequest) String() string            { return proto.CompactTextString(m) }
func (*UnpublishRequest) ProtoMessage()               {}
func (*UnpublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UnpublishRequest) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

type UnpublishResponse struct {
}

func (m *UnpublishResponse) Reset()                    { *m = UnpublishResponse{} }
func (m *UnpublishResponse) String() string            { return proto.CompactTextString(m) }
func (*UnpublishResponse) ProtoMessage()               {}
func (*UnpublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type SetRouteRequest struct {
	Name   string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Routes []*Route `protobuf:"bytes,2,rep,name=routes" json:"routes,omitempty"`
}

func (m *SetRouteRequest) Reset()                    { *m = SetRouteRequest{} }
func (m *SetRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRouteRequest) ProtoMessage()               {}
func (*SetRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SetRouteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetRouteRequest) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type SetRouteResponse struct {
}

func (m *SetRouteResponse) Reset()                    { *m = SetRouteResponse{} }
func (m *SetRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*SetRouteResponse) ProtoMessage()               {}
func (*SetRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type ListRoutesRequest struct {
}

func (m *ListRoutesRequest) Reset()                    { *m = ListRoutesRequest{} }
func (m *ListRoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRoutesRequest) ProtoMessage()               {}
func (*ListRoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type ListRoutesResponse struct {
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
}

func (m *ListRoutesResponse) Reset()                    { *m = ListRoutesResponse{} }
func (m *ListRoutesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListRoutesResponse) ProtoMessage()               {}
func (*ListRoutesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ListRoutesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type LookupRouteRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *LookupRouteRequest) Reset()                    { *m = LookupRouteRequest{} }
func (m *LookupRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*LookupRouteRequest) ProtoMessage()               {}
func (*LookupRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *LookupRouteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LookupRouteResponse struct {
	Routes []*Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
}

func (m *LookupRouteResponse) Reset()                    { *m = LookupRouteResponse{} }
func (m *LookupRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupRouteResponse) ProtoMessage()               {}
func (*LookupRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *LookupRouteResponse) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type StreamServicesRequest struct {
}

func (m *StreamServicesRequest) Reset()                    { *m = StreamServicesRequest{} }
func (m *StreamServicesRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamServicesRequest) ProtoMessage()               {}
func (*StreamServicesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type StreamServicesResponse struct {
	Removed []int64          `protobuf:"zigzag64,1,rep,packed,name=removed" json:"removed,omitempty"`
	Changed []*ServiceChange `protobuf:"bytes,2,rep,name=changed" json:"changed,omitempty"`
}

func (m *StreamServicesResponse) Reset()                    { *m = StreamServicesResponse{} }
func (m *StreamServicesResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamServicesResponse) ProtoMessage()               {}
func (*StreamServicesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *StreamServicesResponse) GetRemoved() []int64 {
	if m != nil {
		return m.Removed
	}
	return nil
}

func (m *StreamServicesResponse) GetChanged() []*ServiceChange {
	if m != nil {
		return m.Changed
	}
	return nil
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "protocol.Endpoint")
	proto.RegisterType((*SubscribeOption)(nil), "protocol.SubscribeOption")
	proto.RegisterType((*PublishSettings)(nil), "protocol.PublishSettings")
	proto.RegisterType((*Route)(nil), "protocol.Route")
	proto.RegisterType((*ServiceChange)(nil), "protocol.ServiceChange")
	proto.RegisterType((*SubscribeRequest)(nil), "protocol.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "protocol.SubscribeResponse")
	proto.RegisterType((*GetEndpointsRequest)(nil), "protocol.GetEndpointsRequest")
	proto.RegisterType((*GetEndpointsResponse)(nil), "protocol.GetEndpointsResponse")
	proto.RegisterType((*StreamEndpointsRequest)(nil), "protocol.StreamEndpointsRequest")
	proto.RegisterType((*StreamEndpointsResponse)(nil), "protocol.StreamEndpointsResponse")
	proto.RegisterType((*UnsubscribeRequest)(nil), "protocol.UnsubscribeRequest")
	proto.RegisterType((*UnsubscribeResponse)(nil), "protocol.UnsubscribeResponse")
	proto.RegisterType((*PublishRequest)(nil), "protocol.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "protocol.PublishResponse")
	proto.RegisterType((*UnpublishRequest)(nil), "protocol.UnpublishRequest")
	proto.RegisterType((*UnpublishResponse)(nil), "protocol.UnpublishResponse")
	proto.RegisterType((*SetRouteRequest)(nil), "protocol.SetRouteRequest")
	proto.RegisterType((*SetRouteResponse)(nil), "protocol.SetRouteResponse")
	proto.RegisterType((*ListRoutesRequest)(nil), "protocol.ListRoutesRequest")
	proto.RegisterType((*ListRoutesResponse)(nil), "protocol.ListRoutesResponse")
	proto.RegisterType((*LookupRouteRequest)(nil), "protocol.LookupRouteRequest")
	proto.RegisterType((*LookupRouteResponse)(nil), "protocol.LookupRouteResponse")
	proto.RegisterType((*StreamServicesRequest)(nil), "protocol.StreamServicesRequest")
	proto.RegisterType((*StreamServicesResponse)(nil), "protocol.StreamServicesResponse")
	proto.RegisterEnum("protocol.RequestType", RequestType_name, RequestType_value)
}

func init() { proto.RegisterFile("copper.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5b, 0x6f, 0xda, 0x30,
	0x14, 0x5e, 0xa0, 0x40, 0x38, 0xdc, 0x8c, 0xe9, 0x85, 0xdd, 0x24, 0x66, 0x69, 0x1a, 0xaa, 0xa6,
	0xae, 0x17, 0xf5, 0x75, 0x0f, 0xbb, 0x68, 0x9b, 0x54, 0x75, 0x53, 0x68, 0x9f, 0xf6, 0x80, 0x42,
	0x62, 0x51, 0xab, 0xc5, 0x0e, 0xb1, 0x53, 0xda, 0xfe, 0x8b, 0xfd, 0xa5, 0xfd, 0xb2, 0x29, 0x89,
	0x9d, 0x04, 0xaa, 0xb1, 0x6e, 0xda, 0x13, 0x9c, 0xe3, 0xcf, 0xdf, 0xf9, 0xce, 0x39, 0x5f, 0x0c,
	0x4d, 0x4f, 0x04, 0x01, 0x0d, 0xf7, 0x82, 0x50, 0x28, 0x81, 0xed, 0xe4, 0xc7, 0x13, 0x57, 0xe4,
	0x3b, 0xd8, 0x1f, 0xb9, 0x1f, 0x08, 0xc6, 0x15, 0xee, 0x43, 0x8d, 0x53, 0xb5, 0x10, 0xe1, 0x65,
	0xdf, 0x1a, 0x58, 0xc3, 0xba, 0x63, 0xc2, 0xf8, 0xc4, 0xf5, 0xfd, 0x90, 0x4a, 0xd9, 0x2f, 0xa5,
	0x27, 0x3a, 0xc4, 0x4f, 0xa1, 0xae, 0xdc, 0x70, 0x4a, 0xd5, 0x98, 0xf9, 0xfd, 0xf2, 0xc0, 0x1a,
	0x62, 0xc7, 0x4e, 0x13, 0x5f, 0x7c, 0x32, 0x87, 0xce, 0x28, 0x9a, 0x48, 0x2f, 0x64, 0x13, 0xfa,
	0x35, 0x50, 0x4c, 0xf0, 0x98, 0x49, 0xd2, 0xf0, 0x9a, 0x79, 0xd4, 0xd4, 0xd0, 0x21, 0x7e, 0x01,
	0xcd, 0x19, 0xe3, 0x63, 0x9f, 0x49, 0xe5, 0x72, 0x8f, 0x26, 0x85, 0x5a, 0x4e, 0x63, 0xc6, 0xf8,
	0x07, 0x9d, 0x4a, 0x20, 0xee, 0x4d, 0x0e, 0x29, 0x6b, 0x88, 0x7b, 0x63, 0x20, 0xe4, 0x87, 0x05,
	0x9d, 0x6f, 0xd1, 0xe4, 0x8a, 0xc9, 0x8b, 0x11, 0x55, 0x8a, 0xf1, 0xa9, 0xc4, 0x4f, 0xc0, 0x0e,
	0x42, 0x26, 0x42, 0xa6, 0x6e, 0x93, 0xa2, 0x2d, 0x27, 0x8b, 0xef, 0x51, 0x96, 0xee, 0x51, 0xe2,
	0x01, 0x34, 0x3c, 0xc1, 0xbd, 0x28, 0x0c, 0x29, 0xf7, 0x6e, 0x4d, 0xd1, 0x42, 0x0a, 0x3f, 0x07,
	0x98, 0x47, 0x34, 0xa2, 0x63, 0xc9, 0xee, 0x68, 0x7f, 0x23, 0x01, 0xd4, 0x93, 0xcc, 0x88, 0xdd,
	0x51, 0x72, 0x06, 0x15, 0x47, 0x44, 0x8a, 0xe2, 0x23, 0xa8, 0x89, 0x64, 0x0c, 0xb2, 0x6f, 0x0d,
	0xca, 0xc3, 0xc6, 0xe1, 0xe3, 0x3d, 0xb3, 0x88, 0xbd, 0x95, 0x41, 0x39, 0x06, 0x89, 0xb7, 0xa1,
	0xba, 0xa0, 0x6c, 0x7a, 0xa1, 0xb4, 0x36, 0x1d, 0x91, 0x05, 0xb4, 0x46, 0xe9, 0xe8, 0xde, 0x5f,
	0xb8, 0x7c, 0x4a, 0x97, 0x57, 0x61, 0x2d, 0xaf, 0x02, 0x63, 0xd8, 0xe0, 0xee, 0x8c, 0xea, 0xf5,
	0x25, 0xff, 0xf1, 0x31, 0xd8, 0x52, 0xcf, 0x28, 0xe9, 0x6a, 0x49, 0xcf, 0xca, 0x10, 0x9d, 0x0c,
	0x4a, 0x38, 0xa0, 0x4c, 0xac, 0x43, 0xe7, 0x11, 0x95, 0xea, 0xdf, 0x3a, 0x7b, 0x09, 0x6d, 0x9f,
	0x49, 0x77, 0x72, 0x45, 0xc7, 0x61, 0x3c, 0x9f, 0xd4, 0x5c, 0xb6, 0xd3, 0xd2, 0xd9, 0x64, 0x68,
	0x92, 0xec, 0x43, 0xb7, 0x50, 0x4f, 0x06, 0x82, 0xcb, 0xf5, 0xcd, 0x92, 0x43, 0xe8, 0x7d, 0xa2,
	0xca, 0xf8, 0x5a, 0x1a, 0x91, 0x6b, 0xef, 0x7c, 0x86, 0xcd, 0xe5, 0x3b, 0xba, 0xd0, 0x3e, 0xd4,
	0xa9, 0x49, 0xea, 0xde, 0x70, 0xde, 0x9b, 0xc1, 0x3b, 0x39, 0x88, 0x1c, 0xc3, 0xf6, 0x48, 0x85,
	0xd4, 0x9d, 0xfd, 0x9d, 0x80, 0x39, 0xec, 0xdc, 0xbb, 0xa6, 0x35, 0x0c, 0xa1, 0xe2, 0xfa, 0x3e,
	0xf5, 0xd7, 0xd4, 0x4f, 0x01, 0xf8, 0x35, 0xd4, 0x42, 0x3a, 0x13, 0xd7, 0xd4, 0xef, 0x97, 0x7e,
	0x8b, 0x35, 0x10, 0x72, 0x00, 0xf8, 0x9c, 0xcb, 0xd5, 0x5d, 0xae, 0x55, 0xb9, 0x05, 0xbd, 0xa5,
	0x2b, 0xa9, 0x42, 0x72, 0x03, 0x6d, 0x6d, 0x98, 0x87, 0xb0, 0xfc, 0x4f, 0x37, 0x76, 0xb3, 0xef,
	0x3d, 0x13, 0xf3, 0x06, 0xd0, 0x39, 0x0f, 0x1e, 0x2e, 0x87, 0xf4, 0xa0, 0x5b, 0xb8, 0xa0, 0x59,
	0x4e, 0xa1, 0x33, 0xa2, 0x2a, 0xf1, 0xa0, 0x21, 0x31, 0xb2, 0xad, 0x82, 0xec, 0x57, 0x50, 0xcd,
	0xcc, 0x1b, 0x0f, 0xbc, 0x93, 0x8b, 0x4e, 0xef, 0xea, 0x63, 0x82, 0x01, 0xe5, 0x7c, 0xba, 0x46,
	0x0f, 0xba, 0x27, 0x4c, 0xa6, 0x49, 0xe3, 0x12, 0xb2, 0x0b, 0xb8, 0x98, 0xd4, 0x1e, 0xd8, 0x84,
	0x4a, 0x5c, 0x2f, 0xf5, 0x60, 0xdd, 0x49, 0x03, 0x32, 0x04, 0x7c, 0x22, 0xc4, 0x65, 0x14, 0xfc,
	0x49, 0x27, 0x79, 0x0b, 0xbd, 0x25, 0xa4, 0xa6, 0xcd, 0xe5, 0x5b, 0xeb, 0xe5, 0xef, 0xc0, 0x56,
	0x6a, 0x4f, 0xfd, 0xe8, 0x64, 0x72, 0x99, 0xb1, 0x7b, 0x7e, 0xa0, 0xb9, 0x9f, 0xe5, 0x66, 0x8c,
	0xc9, 0xf1, 0xbb, 0x12, 0xb2, 0x32, 0xf3, 0xe1, 0x03, 0xa8, 0x79, 0xc9, 0xc3, 0x65, 0xac, 0xba,
	0x53, 0x78, 0x32, 0x8a, 0x0f, 0x9b, 0x63, 0x70, 0xbb, 0x3f, 0x2d, 0x68, 0xe8, 0xb2, 0x67, 0xb7,
	0x01, 0xc5, 0x2d, 0xa8, 0x9f, 0xd2, 0x45, 0x5a, 0x1d, 0x3d, 0x8a, 0xc3, 0xec, 0xa1, 0x40, 0x16,
	0x46, 0xd0, 0x2c, 0x7e, 0xd1, 0xa8, 0x84, 0x7b, 0xd0, 0x59, 0xf9, 0xc4, 0x50, 0x19, 0x77, 0xa0,
	0x51, 0x70, 0x34, 0xda, 0xc0, 0x0d, 0xa8, 0x69, 0x47, 0xa1, 0x4a, 0xcc, 0x99, 0x59, 0x03, 0x55,
	0x71, 0x13, 0x6c, 0xb3, 0x44, 0x54, 0xc3, 0x6d, 0x80, 0x7c, 0x53, 0xc8, 0x8e, 0xa9, 0x0a, 0x33,
	0x46, 0x75, 0x8c, 0xa1, 0xbd, 0x3c, 0x1b, 0x04, 0x93, 0x6a, 0xd2, 0xe5, 0xd1, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0x36, 0x6b, 0x51, 0x92, 0x07, 0x00, 0x00,
}
